{% set name = "nskeyedunarchiver" %}
{% set version = "1.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/NSKeyedUnArchiver-{{ version }}.tar.gz
  sha256: eeda0480021817336e0ffeaca80377c1a8f08ecc5fc06be483b48c44bad414f4

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  imports:
    - NSKeyedUnArchiver
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/avibrazil/NSKeyedUnArchiver
  summary: Decodes Apple's NSKeyedArchiver that were archived into text or binary plist files and returns a usable Python dict
  license: LGPL-3.0-or-later
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - ickc
